
import { Profile, Project, Transaction, Notification } from './types';

export const APP_NAME = "প্রজেক্ট খাতা";

export const TRANSLATIONS = {
  bn: {
    // Nav & General
    home: 'হোম',
    projects: 'প্রজেক্ট',
    khata: 'খাতা',
    workers: 'শ্রমিক',
    accounts: 'হিসাব',
    history: 'ইতিহাস',
    give_attendance: 'হাজিরা দিন',
    settings: 'সেটিংস',
    logout: 'লগআউট করুন',
    profile: 'প্রোফাইল',
    reports: 'রিপোর্ট',
    support: 'সাপোর্ট সেন্টার',
    about: 'আমাদের সম্পর্কে',
    account_settings: 'হিসাব সেটিংস',
    app_settings: 'অ্যাপ সেটিংস',
    general: 'সাধারণ',
    language: 'ভাষা (Language)',
    dark_mode: 'ডার্ক মোড',
    security_data: 'নিরাপত্তা ও ডাটা',
    notifications: 'নোটিফিকেশন',
    change_pass: 'পাসওয়ার্ড পরিবর্তন',
    data_backup: 'ডাটা ব্যাকআপ',
    weekly: 'সাপ্তাহিক',
    monthly: 'মাসিক',
    save_settings: 'সেটিংস সেভ করুন',
    
    // Dashboard Stats
    active_projects: 'চলমান প্রজেক্ট',
    active_workers: 'সক্রিয় কর্মী',
    todays_expense: 'আজকের খরচ',
    present_workers: 'উপস্থিত কর্মী',
    total_due: 'মোট বকেয়া বেতন',
    todays_attendance: 'আজকের উপস্থিতি',
    site_expense: 'আজকের সাইট খরচ',
    
    // Quick Actions
    quick_actions: 'কুইক অ্যাকশন',
    tools: 'টুলস',
    add_worker: 'কর্মী +',
    add_project: 'প্রজেক্ট +',
    advance: 'অগ্রিম',
    expense: 'খরচ',
    deposit: 'জমা (আয়)',
    report: 'রিপোর্ট',
    gallery: 'গ্যালারি',
    site_management: 'সাইট ম্যানেজমেন্ট',
    expense_entry: 'খরচ এন্ট্রি',
    labor_payment: 'লেবার পেমেন্ট',
    project_list: 'প্রজেক্ট লিস্ট',
    project_list_desc: 'চলমান প্রজেক্ট এবং ডিটেইলস দেখুন',
    daily_report: 'কাজের রিপোর্ট',
    site_entry: 'সাইট এন্ট্রি (নিজস্ব হাজিরা)',
    material_stock: 'স্টক / ম্যাটেরিয়াল',
    
    // Worker Dashboard
    total_work_days: 'মোট কাজের দিন',
    total_income: 'মোট আয়',
    leave_request: 'ছুটির আবেদন',
    leave_desc: 'অগ্রিম ছুটির জন্য আবেদন করুন',
    ot_calculator: 'ওভারটাইম ক্যালকুলেটর',
    ot_desc: 'আপনার অতিরিক্ত কাজের হিসাব',
    work_note: 'কাজের নোট',
    note_desc: 'ব্যক্তিগত হিসাব রাখুন',
    attendance_done: 'আজকের হাজিরা সম্পন্ন হয়েছে',
    attendance_recorded: 'আপনার উপস্থিতি রেকর্ড করা হয়েছে।',
    start_attendance: 'আজকের হাজিরা দিন',
    select_project_work: 'কাজের প্রজেক্ট সিলেক্ট করুন',
    message_owner: 'মালিককে মেসেজ দিন',
    current_due: 'আপনার বর্তমান বকেয়া বেতন',
    request_advance: 'অগ্রিম বেতন',
    request_advance_desc: 'টাকার প্রয়োজনে আবেদন করুন',

    // Modals & Forms
    income_title: 'জমা (আয়)',
    expense_title: 'নতুন খরচ',
    amount: 'টাকার পরিমাণ',
    description: 'বিবরণ',
    project_optional: 'প্রজেক্ট (অপশনাল)',
    general_project: 'জেনারেল (কোন প্রজেক্ট নয়)',
    confirm_income: 'জমা করুন',
    confirm_expense: 'খরচ নিশ্চিত করুন',
    payment_title: 'শ্রমিক অগ্রিম / পেমেন্ট',
    select_worker: 'কর্মী সিলেক্ট করুন',
    current_due_label: 'বর্তমান বকেয়া:',
    confirm_payment: 'পেমেন্ট সম্পন্ন করুন',
    recent_expense: 'সাম্প্রতিক খরচ',
    no_expense_today: 'আজ কোন খরচ নেই',
    submit_report: 'রিপোর্ট পাঠান',
    upload_photo: 'কাজের ছবি দিন',
    report_desc: 'আজকের কাজের বিবরণ...',
    request_amount: 'কত টাকা প্রয়োজন?',
    material_entry_title: 'মালামাল গ্রহণ',
    item_name: 'আইটেমের নাম (যেমন: সিমেন্ট)',
    quantity: 'পরিমাণ',
    unit: 'একক (যেমন: ব্যাগ, ট্রাক)',
    supplier: 'সাপ্লায়ার (অপশনাল)',
    challan_photo: 'চালানের ছবি',
    submit_entry: 'এন্ট্রি করুন',
    self_entry_title: 'আপনার সাইট এন্ট্রি',
    confirm_self_entry: 'এন্ট্রি নিশ্চিত করুন',
    you_are_present: 'আপনি আজ সাইটে উপস্থিত আছেন',
    
    // Alerts
    due_alert: 'বকেয়া অ্যালার্ট',
    workers_total_due: 'কর্মীদের মোট বকেয়া:',
    pay_now: 'পরিশোধ করুন',
    last_7_days: 'গত ৭ দিনের আয়-ব্যয়',
    income: 'আয়',
    expenditure: 'ব্যয়',
    
    // Misc
    click_list: 'তালিকায় ক্লিক করুন',
    warning_advance: 'সতর্কতা: এটি বকেয়ার চেয়ে বেশি। অতিরিক্ত টাকা অগ্রিম (Advance) হিসেবে গণ্য হবে।',
    source_placeholder: 'উৎস (যেমন: বিল, স্ক্র্যাপ বিক্রি)',
    expense_placeholder: 'খরচের খাত (যেমন: গাড়ি ভাড়া)',
  },
  en: {
    // Nav & General
    home: 'Home',
    projects: 'Projects',
    khata: 'Khata',
    workers: 'Workers',
    accounts: 'Accounts',
    history: 'History',
    give_attendance: 'Attendance',
    settings: 'Settings',
    logout: 'Logout',
    profile: 'Profile',
    reports: 'Reports',
    support: 'Support Center',
    about: 'About Us',
    account_settings: 'Account Settings',
    app_settings: 'App Settings',
    general: 'General',
    language: 'Language',
    dark_mode: 'Dark Mode',
    security_data: 'Security & Data',
    notifications: 'Notifications',
    change_pass: 'Change Password',
    data_backup: 'Data Backup',
    weekly: 'Weekly',
    monthly: 'Monthly',
    save_settings: 'Save Settings',

    // Dashboard Stats
    active_projects: 'Active Projects',
    active_workers: 'Active Workers',
    todays_expense: "Today's Expense",
    present_workers: 'Present Workers',
    total_due: 'Total Due Balance',
    todays_attendance: "Today's Attendance",
    site_expense: "Today's Site Cost",

    // Quick Actions
    quick_actions: 'Quick Actions',
    tools: 'Tools',
    add_worker: 'Worker +',
    add_project: 'Project +',
    advance: 'Advance',
    expense: 'Expense',
    deposit: 'Deposit (In)',
    report: 'Report',
    gallery: 'Gallery',
    site_management: 'Site Management',
    expense_entry: 'Expense Entry',
    labor_payment: 'Labor Payment',
    project_list: 'Project List',
    project_list_desc: 'View active projects and details',
    daily_report: 'Daily Report',
    site_entry: 'Site Entry (Self)',
    material_stock: 'Stock / Material',

    // Worker Dashboard
    total_work_days: 'Total Work Days',
    total_income: 'Total Income',
    leave_request: 'Leave Request',
    leave_desc: 'Apply for leave in advance',
    ot_calculator: 'OT Calculator',
    ot_desc: 'Calculate overtime earnings',
    work_note: 'Work Note',
    note_desc: 'Keep personal notes',
    attendance_done: 'Attendance Completed',
    attendance_recorded: 'Your attendance has been recorded.',
    start_attendance: 'Give Today\'s Attendance',
    select_project_work: 'Select Project for today',
    message_owner: 'Message Owner',
    current_due: 'Your Current Due Balance',
    request_advance: 'Request Salary',
    request_advance_desc: 'Request for advance payment',

    // Modals & Forms
    income_title: 'Deposit (Income)',
    expense_title: 'New Expense',
    amount: 'Amount',
    description: 'Description',
    project_optional: 'Project (Optional)',
    general_project: 'General (No Project)',
    confirm_income: 'Deposit Now',
    confirm_expense: 'Confirm Expense',
    payment_title: 'Worker Payment / Advance',
    select_worker: 'Select Worker',
    current_due_label: 'Current Due:',
    confirm_payment: 'Complete Payment',
    recent_expense: 'Recent Expenses',
    no_expense_today: 'No expenses today',
    submit_report: 'Submit Report',
    upload_photo: 'Upload Photo',
    report_desc: 'Work description...',
    request_amount: 'Required Amount',
    material_entry_title: 'Material Receive',
    item_name: 'Item Name (e.g. Cement)',
    quantity: 'Quantity',
    unit: 'Unit (e.g. Bag)',
    supplier: 'Supplier (Optional)',
    challan_photo: 'Challan Photo',
    submit_entry: 'Submit Entry',
    self_entry_title: 'Your Site Entry',
    confirm_self_entry: 'Confirm Entry',
    you_are_present: 'You are present at site',

    // Alerts
    due_alert: 'Due Alert',
    workers_total_due: 'Total Workers Due:',
    pay_now: 'Pay Now',
    last_7_days: 'Last 7 Days Income/Expense',
    income: 'Income',
    expenditure: 'Expense',

    // Misc
    click_list: 'Click on list',
    warning_advance: 'Warning: Amount exceeds due. Excess will be treated as Advance.',
    source_placeholder: 'Source (e.g. Bill, Scrap Sale)',
    expense_placeholder: 'Expense Head (e.g. Transport)',
  }
};
